export const LOAD_USER_ABILITIES = 'app/LOAD_USER_ABILITIES';
export const USER_ABILITIES_LOADING_SUCCESS = 'app/USER_ABILITIES_LOADING_SUCCESS';
export const USER_ABILITIES_LOADING_ERROR = 'app/USER_ABILITIES_LOADING_ERROR';
