module.exports = {
	boolean:          require('../../fields/types/boolean/boolean'),
	date:             require('../../fields/types/date/date'),
	datetime:         require('../../fields/types/datetime/datetime'),
	email:            require('../../fields/types/email/email'),
	location:         require('../../fields/types/location/location'),
	markdown:         require('../../fields/types/markdown/markdown'),
	name:             require('../../fields/types/name/name'),
	password:         require('../../fields/types/password/password'),
	select:           require('../../fields/types/select/select'),
	text:             require('../../fields/types/text/text'),
	key:              require('../../fields/types/key/key'),
	textarea:         require('../../fields/types/textarea/textarea'),
	url:              require('../../fields/types/url/url'),
	embedly:          require('../../fields/types/embedly/embedly'),
	color:            require('../../fields/types/color/color'),
	textarray:        require('../../fields/types/textarray/textarray'),
	numberarray:      require('../../fields/types/textarray/textarray'),
	code:             require('../../fields/types/code/code'),
	cloudinaryimage:  require('../../fields/types/cloudinaryimage/cloudinaryimage'),
	cloudinaryimages: require('../../fields/types/cloudinaryimages/cloudinaryimages')
};
