module.exports = {
	boolean:          require('../../fields/types/boolean/boolean'),
	date:             require('../../fields/types/date/date'),
	datetime:         require('../../fields/types/datetime/datetime'),
	email:            require('../../fields/types/email/email'),
	location:         require('../../fields/types/location/location'),
	markdown:         require('../../fields/types/markdown/markdown'),
	name:             require('../../fields/types/name/name'),
	password:         require('../../fields/types/password/password'),
	select:           require('../../fields/types/select/select'),
	text:             require('../../fields/types/text/text'),
	key:              require('../../fields/types/key/key'),
	textarea:         require('../../fields/types/textarea/textarea'),
	url:              require('../../fields/types/url/url'),
	embedly:          require('../../fields/types/embedly/embedly'),
	color:            require('../../fields/types/color/color'),
	relationship:     require('../../fields/types/relationship/relationship'),
	s3file:           require('../../fields/types/s3file/s3file'),
	azurefile:        require('../../fields/types/azurefile/azurefile'),
	localfile:  	  require('../../fields/types/localfile/localfile'),
	textarray:        require('../../fields/types/textarray/textarray'),
	numberarray:      require('../../fields/types/numberarray/numberarray'),
	code:             require('../../fields/types/code/code'),
	number:           require('../../fields/types/number/number'),
	html:             require('../../fields/types/html/html'),
	cloudinaryimage:  require('../../fields/types/cloudinaryimage/cloudinaryimage'),
	cloudinaryimages: require('../../fields/types/cloudinaryimages/cloudinaryimages')
};
