module.exports = {
	azurefile:        require('../../fields/types/azurefile/AzureFileFilter'),
	boolean:          require('../../fields/types/boolean/BooleanFilter'),
	cloudinaryimage:  require('../../fields/types/cloudinaryimage/CloudinaryImageFilter'),
	cloudinaryimages: require('../../fields/types/cloudinaryimages/CloudinaryImagesFilter'),
	code:             require('../../fields/types/code/CodeFilter'),
	color:            require('../../fields/types/color/ColorFilter'),
	date:             require('../../fields/types/date/DateFilter'),
	datearray:        require('../../fields/types/datearray/DateArrayFilter'),
	datetime:         require('../../fields/types/datetime/DatetimeFilter'),
	email:            require('../../fields/types/email/EmailFilter'),
	embedly:          require('../../fields/types/embedly/EmbedlyFilter'),
	// geopoint:         require('../../fields/types/geopoint/GeoPointFilter'),
	html:             require('../../fields/types/html/HtmlFilter'),
	key:              require('../../fields/types/key/KeyFilter'),
	localfile:  	  require('../../fields/types/localfile/LocalFileFilter'),
	localfiles:       require('../../fields/types/localfiles/LocalFilesFilter'),
	location:         require('../../fields/types/location/LocationFilter'),
	markdown:         require('../../fields/types/markdown/MarkdownFilter'),
	money:            require('../../fields/types/money/MoneyFilter'),
	name:             require('../../fields/types/name/NameFilter'),
	number:           require('../../fields/types/number/NumberFilter'),
	numberarray:      require('../../fields/types/numberarray/NumberArrayFilter'),
	password:         require('../../fields/types/password/PasswordFilter'),
	relationship:     require('../../fields/types/relationship/RelationshipFilter'),
	s3file:           require('../../fields/types/s3file/S3FileFilter'),
	select:           require('../../fields/types/select/SelectFilter'),
	text:             require('../../fields/types/text/TextFilter'),
	textarea:         require('../../fields/types/textarea/TextareaFilter'),
	textarray:        require('../../fields/types/textarray/TextArrayFilter'),
	url:              require('../../fields/types/url/UrlFilter')
};
