// This file exports the common packages required by the Admin UI.
//
// It is used to build /public/js/packages.js, and exclude these packages from
// the Admin UI bundle generated by browserify.
module.exports = [
	'blacklist',
	'bytes',
	'classnames',
	'history',
	'i',
	'list-to-array',
	'marked',
	'moment',
	'numeral',
	'pikaday',
	'qs',
	'react-addons-css-transition-group',
	'react-alt-text',
	'react-dom',
	'react-select',
	'react',
	'store-prototype',
	'superagent',
	'underscore',
	'vkey',
	'xhr',
];
