export const LOAD_COUNTS = 'app/Home/LOAD_COUNTS';
export const COUNTS_LOADING_SUCCESS = 'app/Home/COUNTS_LOADING_SUCCESS';
export const COUNTS_LOADING_ERROR = 'app/Home/COUNTS_LOADING_ERROR';
export const LOAD_USER_ABILITIES = 'app/Home/LOAD_USER_ABILITIES';
export const USER_ABILITIES_LOADING_SUCCESS = 'app/Home/USER_ABILITIES_LOADING_SUCCESS';
export const USER_ABILITIES_LOADING_ERROR = 'app/Home/USER_ABILITIES_LOADING_ERROR';

