module.exports = {
	Field: require('../CloudinaryImageField'),
	Filter: require('../CloudinaryImageFilter'),
	section: 'Miscellaneous',
	spec: {
		label: 'CloudinaryImage',
		path: 'cloudinaryimage',
		paths: {
			action: 'cloudinaryimage_action',
			exists: 'cloudinaryimage.exists',
			folder: 'cloudinaryimage.folder',
			format: 'cloudinaryimage.format',
			height: 'cloudinaryimage.height',
			public_id: 'cloudinaryimage.public_id',
			resource_type: 'cloudinaryimage.resource_type',
			secure_url: 'cloudinaryimage.secure_url',
			select: 'cloudinaryimage.select',
			signature: 'cloudinaryimage.signature',
			upload: 'cloudinaryimage_upload',
			url: 'cloudinaryimage.url',
			version: 'cloudinaryimage.version',
			width: 'cloudinaryimage.width',
		},
		value: {
			format: null,
			height: null,
			public_id: null,
			resource_type: null,
			secure_url: null,
			signature: null,
			url: null,
			version: null,
			width: null,
		},
	},
};
